spring:
  application:
    name: spreadsheet
  datasource:
    url: jdbc:mysql://localhost:3306/<DATABASE_NAME>
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <MYSQL_USERNAME>
    password: <MYSQL_PASSWORD>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  profiles:
    active: local
server:
  port: 8080